cabal-version:      3.16
name:               hdoom
version:            0.1.0.0
license:            NONE
author:             evanrinehart@gmail.com
maintainer:         Evan Rinehart
build-type:         Simple
extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    hs-source-dirs: lib
    exposed-modules:
        RGBA, Name8, Offset, Input, Buffer8, Wave, Palette, Patch, Level, Fix16, Number,
        DoomKeys, RNG, KnownIWADs, LumpDirectory,
        Clock, AbstractFilePath, FileSystem, FPS, 
        Loader, LoadWord, BlobParsers,
        Video, Audio, Raylib, Draw, FrameBuffer, Gamepad, ColorBuffer,
        WadFile,
        Nodes, PackedNodes, AreaTree, Four, Geometry,
    build-depends:  base ^>=4.20.0.0, vector, mtl, primitive, bytestring, containers,
                    unordered-containers, hashable, clock, directory, filepath, file-io, stm,
                    hdoom:nuts-n-bolts
    -- default-language: Haskell2010
    ghc-options: -O2

library nuts-n-bolts
    hs-source-dirs: lib
    exposed-modules:
        MobjType, StateName, SfxName, MobjFlags, CodePointer, SpriteNum,
        MobjInfo, MobjStates,
        Number
    build-depends:  base ^>=4.20.0.0,
    build-tool-depends: hdoom:makeinfo

executable hdoom
    import:           warnings
    main-is:          Main.hs
    build-depends:    base ^>=4.20.0.0, hdoom, hdoom:nuts-n-bolts
    hs-source-dirs:   app
    -- default-language: Haskell2010
    ghc-options: -threaded -O2

    include-dirs: cbits/

    c-sources: cbits/raylib_glue.c

    extra-lib-dirs:   cbits
    extra-libraries:
        raylib
        X11

executable makeinfo
    main-is: MakeInfo.hs
    other-modules:
        MobjType, StateName, SfxName, MobjFlags, CodePointer, SpriteNum,
        MakeInfoTable, MakeStateTable,
        Utils
    hs-source-dirs: tools
    build-depends: base, mtl
