{-# LANGUAGE PatternSynonyms #-}
module Gamepad where

import Foreign.C.Types

pattern GAMEPAD_BUTTON_UNKNOWN :: CInt
pattern GAMEPAD_BUTTON_UNKNOWN = 0

pattern GAMEPAD_BUTTON_LEFT_FACE_UP :: CInt
pattern GAMEPAD_BUTTON_LEFT_FACE_UP = 1

pattern GAMEPAD_BUTTON_LEFT_FACE_RIGHT :: CInt
pattern GAMEPAD_BUTTON_LEFT_FACE_RIGHT = 2

pattern GAMEPAD_BUTTON_LEFT_FACE_DOWN :: CInt
pattern GAMEPAD_BUTTON_LEFT_FACE_DOWN = 3

pattern GAMEPAD_BUTTON_LEFT_FACE_LEFT :: CInt
pattern GAMEPAD_BUTTON_LEFT_FACE_LEFT = 4

pattern GAMEPAD_BUTTON_RIGHT_FACE_UP :: CInt
pattern GAMEPAD_BUTTON_RIGHT_FACE_UP = 5

pattern GAMEPAD_BUTTON_RIGHT_FACE_RIGHT:: CInt
pattern GAMEPAD_BUTTON_RIGHT_FACE_RIGHT = 6

pattern GAMEPAD_BUTTON_RIGHT_FACE_DOWN :: CInt
pattern GAMEPAD_BUTTON_RIGHT_FACE_DOWN = 7

pattern GAMEPAD_BUTTON_RIGHT_FACE_LEFT :: CInt
pattern GAMEPAD_BUTTON_RIGHT_FACE_LEFT = 8

pattern GAMEPAD_BUTTON_LEFT_TRIGGER_1 :: CInt
pattern GAMEPAD_BUTTON_LEFT_TRIGGER_1 = 9

pattern GAMEPAD_BUTTON_LEFT_TRIGGER_2 :: CInt
pattern GAMEPAD_BUTTON_LEFT_TRIGGER_2 = 10

pattern GAMEPAD_BUTTON_RIGHT_TRIGGER_1 :: CInt
pattern GAMEPAD_BUTTON_RIGHT_TRIGGER_1 = 11

pattern GAMEPAD_BUTTON_RIGHT_TRIGGER_2 :: CInt
pattern GAMEPAD_BUTTON_RIGHT_TRIGGER_2 = 12
